apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbit.fullname" . }}-backend
  labels:
    {{- include "orbit.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
  selector:
    {{- include "orbit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
