apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbit.fullname" . }}-frontend
  labels:
    {{- include "orbit.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
  selector:
    {{- include "orbit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
