apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbit.fullname" . }}-ipam
  labels:
    {{- include "orbit.labels" . | nindent 4 }}
    app.kubernetes.io/component: ipam
spec:
  ports:
    - port: {{ .Values.ipam.service.port }}
      targetPort: 8081
  selector:
    {{- include "orbit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ipam
