apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbit.fullname" . }}-secret
  labels:
    {{- include "orbit.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwtSecret | quote }}
  {{- if not .Values.postgres.existingSecret }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  {{- end }}
