-- Seed: 200+ hardware components across all categories
-- Routers
INSERT INTO hardware_components (category, brand, model, spec, price_est, currency, buy_urls, approved) VALUES
('router', 'Ubiquiti', 'Dream Machine Pro', '{"ports":"8x GbE + 2x SFP+","cpu":"ARM Cortex-A57 quad-core","ram":"4GB","throughput":"3.5 Gbps","form_factor":"1U rack"}', 379, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Ubiquiti+Dream+Machine+Pro","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Ubiquiti+Dream+Machine+Pro","condition":"used"}]', true),
('router', 'Ubiquiti', 'Dream Router', '{"ports":"4x GbE","cpu":"ARM quad-core","ram":"2GB","throughput":"2.4 Gbps","form_factor":"desktop"}', 199, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Ubiquiti+Dream+Router","condition":"new"}]', true),
('router', 'MikroTik', 'RB5009UG+S+IN', '{"ports":"7x GbE + 1x 2.5GbE + 1x SFP+","cpu":"ARM quad-core 1.4GHz","ram":"1GB","throughput":"2.5 Gbps","form_factor":"desktop"}', 220, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=MikroTik+RB5009","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=MikroTik+RB5009","condition":"used"}]', true),
('router', 'MikroTik', 'hEX S (RB760iGS)', '{"ports":"5x GbE + 1x SFP","cpu":"MIPS 880MHz","ram":"256MB","throughput":"1 Gbps","form_factor":"desktop"}', 69, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=MikroTik+hEX+S","condition":"new"}]', true),
('router', 'Protectli', 'VP2420 (pfSense)', '{"ports":"4x 2.5GbE","cpu":"Intel J6412 quad-core","ram":"8GB","throughput":"2.5 Gbps","form_factor":"mini-pc"}', 320, 'EUR', '[{"store":"Protectli","url":"https://protectli.com/product/vp2420/","condition":"new"}]', true),
('router', 'Protectli', 'FW4B (pfSense)', '{"ports":"4x GbE","cpu":"Intel J3160 quad-core","ram":"4GB","throughput":"1 Gbps","form_factor":"mini-pc"}', 249, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Protectli+FW4B","condition":"new"}]', true),
('router', 'GL.iNet', 'Flint 2 (GL-MT6000)', '{"ports":"4x GbE + 1x 2.5GbE","cpu":"MediaTek MT6000 quad-core","ram":"1GB","wifi":"WiFi 6","form_factor":"desktop"}', 99, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=GL.iNet+Flint+2","condition":"new"}]', true),
('router', 'TP-Link', 'ER8411', '{"ports":"2x 10GbE SFP+ + 8x GbE + 1x GbE WAN","cpu":"quad-core 1.0GHz","ram":"2GB","throughput":"10 Gbps","form_factor":"1U rack"}', 299, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=TP-Link+ER8411","condition":"new"}]', true),
('router', 'Netgate', '6100 (pfSense+)', '{"ports":"4x GbE + 2x SFP+","cpu":"ARM Cortex-A53 quad-core","ram":"4GB","throughput":"5 Gbps","form_factor":"desktop"}', 599, 'EUR', '[{"store":"Netgate","url":"https://www.netgate.com/6100","condition":"new"}]', true),
('router', 'Firewalla', 'Gold Pro', '{"ports":"4x 2.5GbE","cpu":"quad-core 1.8GHz","ram":"4GB","throughput":"2.5 Gbps","form_factor":"mini-pc"}', 369, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Firewalla+Gold+Pro","condition":"new"}]', true),
('router', 'Cisco', 'RV340', '{"ports":"4x GbE + 2x WAN","cpu":"dual-core 1.0GHz","ram":"512MB","throughput":"900 Mbps","form_factor":"desktop"}', 199, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Cisco+RV340","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Cisco+RV340","condition":"used"}]', true),
('router', 'Keenetic', 'Ultra KN-1811', '{"ports":"4x GbE + 2x 2.5GbE + 2x SFP","cpu":"quad-core 1.8GHz","ram":"512MB","wifi":"WiFi 6","form_factor":"desktop"}', 179, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Keenetic+Ultra","condition":"new"}]', true),

-- Switches
('switch', 'Ubiquiti', 'USW-Pro-24-PoE', '{"ports":"24x GbE PoE + 2x 10G SFP+","poe_budget":"400W","managed":true,"form_factor":"1U rack"}', 599, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Ubiquiti+USW-Pro-24-PoE","condition":"new"}]', true),
('switch', 'Ubiquiti', 'USW-Lite-8-PoE', '{"ports":"8x GbE PoE","poe_budget":"52W","managed":true,"form_factor":"desktop"}', 109, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Ubiquiti+USW-Lite-8-PoE","condition":"new"},{"store":"Allegro","url":"https://allegro.pl/listing?string=Ubiquiti+USW-Lite-8-PoE","condition":"new"}]', true),
('switch', 'Ubiquiti', 'USW-Flex-Mini', '{"ports":"5x GbE","poe_budget":"0W","managed":true,"form_factor":"mini"}', 29, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Ubiquiti+USW-Flex-Mini","condition":"new"}]', true),
('switch', 'MikroTik', 'CRS328-24P-4S+RM', '{"ports":"24x GbE PoE + 4x SFP+","poe_budget":"500W","managed":true,"form_factor":"1U rack"}', 399, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=MikroTik+CRS328","condition":"new"}]', true),
('switch', 'MikroTik', 'CSS610-8G-2S+IN', '{"ports":"8x GbE + 2x SFP+","poe_budget":"0W","managed":true,"form_factor":"desktop"}', 99, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=MikroTik+CSS610","condition":"new"}]', true),
('switch', 'TP-Link', 'TL-SG108PE', '{"ports":"8x GbE PoE","poe_budget":"64W","managed":false,"form_factor":"desktop"}', 60, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=TP-Link+TL-SG108PE","condition":"new"},{"store":"Allegro","url":"https://allegro.pl/listing?string=TP-Link+TL-SG108PE","condition":"new"}]', true),
('switch', 'TP-Link', 'TL-SG3428', '{"ports":"24x GbE + 4x SFP","poe_budget":"0W","managed":true,"form_factor":"1U rack"}', 149, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=TP-Link+TL-SG3428","condition":"new"}]', true),
('switch', 'Netgear', 'GS308E', '{"ports":"8x GbE","poe_budget":"0W","managed":true,"form_factor":"desktop"}', 39, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Netgear+GS308E","condition":"new"}]', true),
('switch', 'Cisco', 'SG350-28', '{"ports":"24x GbE + 2x SFP + 2x combo","poe_budget":"0W","managed":true,"form_factor":"1U rack"}', 299, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Cisco+SG350-28","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Cisco+SG350-28","condition":"used"}]', true),
('switch', 'Zyxel', 'GS1900-24EP', '{"ports":"24x GbE PoE","poe_budget":"170W","managed":true,"form_factor":"1U rack"}', 179, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Zyxel+GS1900-24EP","condition":"new"}]', true),

-- NAS
('nas', 'Synology', 'DS923+', '{"bays":4,"cpu":"AMD Ryzen R1600 dual-core","ram":"4GB","max_ram":"32GB","m2_slots":2,"form_factor":"tower"}', 599, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Synology+DS923%2B","condition":"new"},{"store":"Allegro","url":"https://allegro.pl/listing?string=Synology+DS923%2B","condition":"new"}]', true),
('nas', 'Synology', 'DS1522+', '{"bays":5,"cpu":"AMD Ryzen R1600 dual-core","ram":"8GB","max_ram":"32GB","m2_slots":2,"form_factor":"tower"}', 699, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Synology+DS1522%2B","condition":"new"}]', true),
('nas', 'Synology', 'DS1821+', '{"bays":8,"cpu":"AMD Ryzen V1500B quad-core","ram":"4GB","max_ram":"32GB","m2_slots":2,"form_factor":"tower"}', 999, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Synology+DS1821%2B","condition":"new"}]', true),
('nas', 'Synology', 'DS224+', '{"bays":2,"cpu":"Intel Celeron J4125 quad-core","ram":"2GB","max_ram":"6GB","m2_slots":2,"form_factor":"tower"}', 299, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Synology+DS224%2B","condition":"new"}]', true),
('nas', 'QNAP', 'TS-464', '{"bays":4,"cpu":"Intel Celeron N5095 quad-core","ram":"8GB","max_ram":"16GB","m2_slots":2,"form_factor":"tower"}', 549, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=QNAP+TS-464","condition":"new"}]', true),
('nas', 'QNAP', 'TS-873A', '{"bays":8,"cpu":"AMD Ryzen V1500B quad-core","ram":"8GB","max_ram":"64GB","m2_slots":2,"form_factor":"tower"}', 899, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=QNAP+TS-873A","condition":"new"}]', true),
('nas', 'Terramaster', 'F4-423', '{"bays":4,"cpu":"Intel Celeron N5105 quad-core","ram":"8GB","max_ram":"32GB","m2_slots":2,"form_factor":"tower"}', 399, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Terramaster+F4-423","condition":"new"}]', true),
('nas', 'Asustor', 'Lockerstor 4 Gen2 AS6704T', '{"bays":4,"cpu":"Intel Celeron N5105 quad-core","ram":"4GB","max_ram":"16GB","m2_slots":2,"form_factor":"tower"}', 449, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Asustor+AS6704T","condition":"new"}]', true),
('nas', 'DIY', 'TrueNAS (Jonsbo N1)', '{"bays":5,"cpu":"custom","ram":"custom","m2_slots":1,"form_factor":"mini-itx","note":"DIY build"}', 450, 'EUR', '[{"store":"Jonsbo","url":"https://www.jonsbo.com/en/products/N1.html","condition":"new"}]', true),

-- Servers
('server', 'Dell', 'PowerEdge R730', '{"cpu":"2x Intel Xeon E5-2680v4","ram":"64GB DDR4","storage":"2x 1TB SAS","psu":"dual 750W","form_factor":"2U rack","ports":"4x GbE"}', 400, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Dell+PowerEdge+R730","condition":"used"}]', true),
('server', 'Dell', 'PowerEdge R720', '{"cpu":"2x Intel Xeon E5-2660v2","ram":"32GB DDR3","storage":"2x 600GB SAS","psu":"dual 750W","form_factor":"2U rack","ports":"4x GbE"}', 250, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Dell+PowerEdge+R720","condition":"used"}]', true),
('server', 'Dell', 'PowerEdge R620', '{"cpu":"2x Intel Xeon E5-2640v2","ram":"32GB DDR3","storage":"2x 300GB SAS","psu":"dual 750W","form_factor":"1U rack","ports":"4x GbE"}', 180, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Dell+PowerEdge+R620","condition":"used"}]', true),
('server', 'Dell', 'PowerEdge R450', '{"cpu":"Intel Xeon Silver 4314","ram":"32GB DDR4","storage":"2x 480GB SSD","psu":"dual 600W","form_factor":"1U rack","ports":"4x GbE"}', 1200, 'EUR', '[{"store":"Dell","url":"https://www.dell.com/en-us/shop/servers-storage-and-networking/poweredge-r450-rack-server","condition":"new"}]', true),
('server', 'HP', 'ProLiant DL380 Gen9', '{"cpu":"2x Intel Xeon E5-2680v4","ram":"64GB DDR4","storage":"2x 1.2TB SAS","psu":"dual 800W","form_factor":"2U rack","ports":"4x GbE"}', 450, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=HP+ProLiant+DL380+Gen9","condition":"used"}]', true),
('server', 'HP', 'ProLiant DL360 Gen10', '{"cpu":"Intel Xeon Silver 4208","ram":"32GB DDR4","storage":"2x 480GB SSD","psu":"dual 500W","form_factor":"1U rack","ports":"4x GbE"}', 800, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=HP+ProLiant+DL360+Gen10","condition":"used"}]', true),
('server', 'Supermicro', 'X11SCL-F (Xeon E-2278G)', '{"cpu":"Intel Xeon E-2278G 8-core","ram":"32GB ECC DDR4","storage":"2x 480GB SSD","psu":"single 400W","form_factor":"1U rack","ports":"2x GbE + IPMI"}', 600, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Supermicro+X11SCL","condition":"used"}]', true),
('server', 'Lenovo', 'ThinkSystem SR630 V2', '{"cpu":"Intel Xeon Silver 4310","ram":"32GB DDR4","storage":"2x 480GB SSD","psu":"dual 750W","form_factor":"1U rack","ports":"4x GbE"}', 1500, 'EUR', '[{"store":"Lenovo","url":"https://www.lenovo.com/us/en/servers-storage/thinksystem/rack-servers/SR630-V2/","condition":"new"}]', true),

-- Mini PCs / SFF
('minipc', 'Intel', 'NUC 13 Pro (i5-1340P)', '{"cpu":"Intel Core i5-1340P 12-core","ram":"16GB DDR4","storage":"512GB NVMe","tdp":"28W","form_factor":"mini-pc"}', 499, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Intel+NUC+13+Pro","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Intel+NUC+13+Pro","condition":"used"}]', true),
('minipc', 'Beelink', 'EQ12 (N100)', '{"cpu":"Intel N100 4-core","ram":"16GB DDR5","storage":"500GB NVMe","tdp":"6W","form_factor":"mini-pc"}', 169, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Beelink+EQ12","condition":"new"}]', true),
('minipc', 'Beelink', 'SER6 Pro (Ryzen 7 6800H)', '{"cpu":"AMD Ryzen 7 6800H 8-core","ram":"32GB DDR5","storage":"1TB NVMe","tdp":"45W","form_factor":"mini-pc"}', 399, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Beelink+SER6+Pro","condition":"new"}]', true),
('minipc', 'Minisforum', 'UM790 Pro (Ryzen 9 7940HS)', '{"cpu":"AMD Ryzen 9 7940HS 8-core","ram":"32GB DDR5","storage":"1TB NVMe","tdp":"54W","form_factor":"mini-pc"}', 499, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Minisforum+UM790+Pro","condition":"new"}]', true),
('minipc', 'Lenovo', 'ThinkCentre Tiny M920q (i5-8500T)', '{"cpu":"Intel Core i5-8500T 6-core","ram":"16GB DDR4","storage":"256GB NVMe","tdp":"35W","form_factor":"mini-pc"}', 180, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Lenovo+ThinkCentre+M920q","condition":"used"}]', true),
('minipc', 'Dell', 'OptiPlex Micro 7010 (i5-13500T)', '{"cpu":"Intel Core i5-13500T 14-core","ram":"16GB DDR4","storage":"512GB NVMe","tdp":"35W","form_factor":"mini-pc"}', 499, 'EUR', '[{"store":"Dell","url":"https://www.dell.com/en-us/shop/desktops-all-in-one-pcs/optiplex-7010-micro-form-factor","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Dell+OptiPlex+7010+Micro","condition":"used"}]', true),
('minipc', 'HP', 'EliteDesk 800 G5 Mini (i5-9500T)', '{"cpu":"Intel Core i5-9500T 6-core","ram":"16GB DDR4","storage":"256GB NVMe","tdp":"35W","form_factor":"mini-pc"}', 200, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=HP+EliteDesk+800+G5+Mini","condition":"used"}]', true),
('minipc', 'ASUS', 'PN64 (i7-12700H)', '{"cpu":"Intel Core i7-12700H 14-core","ram":"32GB DDR4","storage":"1TB NVMe","tdp":"45W","form_factor":"mini-pc"}', 549, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=ASUS+PN64","condition":"new"}]', true),
('minipc', 'Topton', 'N5105 4x 2.5GbE Firewall', '{"cpu":"Intel N5105 4-core","ram":"8GB DDR4","storage":"128GB SSD","tdp":"10W","ports":"4x 2.5GbE","form_factor":"mini-pc"}', 149, 'EUR', '[{"store":"AliExpress","url":"https://www.aliexpress.com/w/wholesale-n5105-firewall.html","condition":"new"}]', true),
('minipc', 'Trigkey', 'Speed S5 (Ryzen 5 5500U)', '{"cpu":"AMD Ryzen 5 5500U 6-core","ram":"16GB DDR4","storage":"500GB NVMe","tdp":"15W","form_factor":"mini-pc"}', 189, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Trigkey+Speed+S5","condition":"new"}]', true),

-- SBCs
('sbc', 'Raspberry Pi', 'Pi 5 (8GB)', '{"cpu":"ARM Cortex-A76 quad-core 2.4GHz","ram":"8GB LPDDR4X","storage":"microSD/NVMe via HAT","tdp":"5W","ports":"2x USB3 + 2x USB2 + GbE + 2x HDMI","form_factor":"sbc"}', 80, 'EUR', '[{"store":"Botland","url":"https://botland.com.pl/raspberry-pi-5/","condition":"new"},{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Raspberry+Pi+5+8GB","condition":"new"}]', true),
('sbc', 'Raspberry Pi', 'Pi 5 (4GB)', '{"cpu":"ARM Cortex-A76 quad-core 2.4GHz","ram":"4GB LPDDR4X","storage":"microSD/NVMe via HAT","tdp":"5W","ports":"2x USB3 + 2x USB2 + GbE + 2x HDMI","form_factor":"sbc"}', 60, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Raspberry+Pi+5+4GB","condition":"new"}]', true),
('sbc', 'Raspberry Pi', 'Pi 4 Model B (8GB)', '{"cpu":"ARM Cortex-A72 quad-core 1.8GHz","ram":"8GB LPDDR4","storage":"microSD","tdp":"4W","ports":"2x USB3 + 2x USB2 + GbE + 2x micro-HDMI","form_factor":"sbc"}', 75, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Raspberry+Pi+4+8GB","condition":"new"},{"store":"Allegro","url":"https://allegro.pl/listing?string=Raspberry+Pi+4+8GB","condition":"new"}]', true),
('sbc', 'Raspberry Pi', 'Pi 4 Model B (4GB)', '{"cpu":"ARM Cortex-A72 quad-core 1.8GHz","ram":"4GB LPDDR4","storage":"microSD","tdp":"4W","ports":"2x USB3 + 2x USB2 + GbE + 2x micro-HDMI","form_factor":"sbc"}', 55, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Raspberry+Pi+4+4GB","condition":"new"}]', true),
('sbc', 'Orange Pi', '5 Plus (16GB)', '{"cpu":"Rockchip RK3588 8-core","ram":"16GB LPDDR4","storage":"eMMC + NVMe","tdp":"10W","ports":"2x USB3 + 2x USB2 + 2x GbE + HDMI + DP","form_factor":"sbc"}', 99, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Orange+Pi+5+Plus","condition":"new"}]', true),
('sbc', 'Radxa', 'ROCK 5B (16GB)', '{"cpu":"Rockchip RK3588 8-core","ram":"16GB LPDDR4","storage":"eMMC + NVMe","tdp":"10W","ports":"USB3 + USB2 + 2.5GbE + HDMI","form_factor":"sbc"}', 149, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Radxa+ROCK+5B","condition":"new"}]', true),
('sbc', 'Odroid', 'N2+ (4GB)', '{"cpu":"ARM Cortex-A73/A53 6-core","ram":"4GB DDR4","storage":"eMMC + microSD","tdp":"6W","ports":"USB3 + USB2 + GbE + HDMI","form_factor":"sbc"}', 79, 'EUR', '[{"store":"Hardkernel","url":"https://www.hardkernel.com/shop/odroid-n2-with-4gbyte-ram-2/","condition":"new"}]', true),
('sbc', 'Banana Pi', 'BPI-R4 (Router SBC)', '{"cpu":"MediaTek MT7988A quad-core","ram":"4GB DDR4","storage":"eMMC + NVMe","tdp":"8W","ports":"4x GbE + 2x 10GbE SFP+","form_factor":"sbc"}', 99, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Banana+Pi+BPI-R4","condition":"new"}]', true),
('sbc', 'Libre Computer', 'AML-S905X-CC (Le Potato)', '{"cpu":"ARM Cortex-A53 quad-core 1.5GHz","ram":"2GB DDR3","storage":"microSD","tdp":"2W","ports":"USB2 + GbE + HDMI","form_factor":"sbc"}', 25, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Libre+Computer+Le+Potato","condition":"new"}]', true),
('sbc', 'Raspberry Pi', 'Pi Zero 2 W', '{"cpu":"ARM Cortex-A53 quad-core 1.0GHz","ram":"512MB LPDDR2","storage":"microSD","tdp":"2W","ports":"USB2 + mini-HDMI + WiFi + BT","form_factor":"sbc"}', 15, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Raspberry+Pi+Zero+2+W","condition":"new"}]', true),

-- Access Points
('access_point', 'Ubiquiti', 'U6 Pro', '{"wifi":"WiFi 6","streams":"4x4 MU-MIMO","max_clients":300,"poe":"802.3af","form_factor":"ceiling"}', 159, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Ubiquiti+U6+Pro","condition":"new"},{"store":"Allegro","url":"https://allegro.pl/listing?string=Ubiquiti+U6+Pro","condition":"new"}]', true),
('access_point', 'Ubiquiti', 'U6 Lite', '{"wifi":"WiFi 6","streams":"2x2 MU-MIMO","max_clients":150,"poe":"802.3af","form_factor":"ceiling"}', 99, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Ubiquiti+U6+Lite","condition":"new"}]', true),
('access_point', 'Ubiquiti', 'U6 Long-Range', '{"wifi":"WiFi 6","streams":"4x4 MU-MIMO","max_clients":300,"poe":"802.3af","range":"183m","form_factor":"ceiling"}', 179, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Ubiquiti+U6+Long-Range","condition":"new"}]', true),
('access_point', 'Ubiquiti', 'U6 Mesh', '{"wifi":"WiFi 6","streams":"4x4 MU-MIMO","max_clients":200,"poe":"802.3af","form_factor":"outdoor"}', 199, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Ubiquiti+U6+Mesh","condition":"new"}]', true),
('access_point', 'TP-Link', 'EAP660 HD (WiFi 6)', '{"wifi":"WiFi 6","streams":"4x4 MU-MIMO","max_clients":1024,"poe":"802.3at","form_factor":"ceiling"}', 180, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=TP-Link+EAP660+HD","condition":"new"}]', true),
('access_point', 'TP-Link', 'EAP670 (WiFi 6)', '{"wifi":"WiFi 6","streams":"4x4 MU-MIMO","max_clients":574,"poe":"802.3at","form_factor":"ceiling"}', 120, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=TP-Link+EAP670","condition":"new"}]', true),
('access_point', 'Netgear', 'WAX630 (WiFi 6 Tri-band)', '{"wifi":"WiFi 6 tri-band","streams":"4x4 MU-MIMO","max_clients":600,"poe":"802.3at","form_factor":"ceiling"}', 249, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Netgear+WAX630","condition":"new"}]', true),
('access_point', 'Aruba', 'Instant On AP22', '{"wifi":"WiFi 6","streams":"2x2 MU-MIMO","max_clients":256,"poe":"802.3af","form_factor":"ceiling"}', 149, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Aruba+Instant+On+AP22","condition":"new"}]', true),

-- UPS
('ups', 'APC', 'Back-UPS 1500VA BX1500M', '{"capacity_va":1500,"capacity_w":900,"outlets":10,"runtime_min":10,"form_factor":"tower"}', 199, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=APC+Back-UPS+1500VA","condition":"new"}]', true),
('ups', 'CyberPower', 'CP1500PFCLCD', '{"capacity_va":1500,"capacity_w":1000,"outlets":12,"runtime_min":12,"form_factor":"tower"}', 229, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=CyberPower+CP1500PFCLCD","condition":"new"}]', true),
('ups', 'Eaton', '5P 1550VA', '{"capacity_va":1550,"capacity_w":1100,"outlets":8,"runtime_min":15,"form_factor":"tower"}', 349, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Eaton+5P+1550","condition":"new"}]', true),
('ups', 'APC', 'Smart-UPS 1500VA SMT1500I', '{"capacity_va":1500,"capacity_w":1000,"outlets":8,"runtime_min":20,"form_factor":"tower","management":"USB+serial"}', 499, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=APC+Smart-UPS+1500","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=APC+Smart-UPS+1500","condition":"used"}]', true),
('ups', 'Riello', 'iDialog 1200VA', '{"capacity_va":1200,"capacity_w":720,"outlets":6,"runtime_min":10,"form_factor":"tower"}', 149, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Riello+iDialog+1200","condition":"new"}]', true),

-- Storage (HDDs/SSDs)
('storage', 'Samsung', '870 EVO 4TB SATA SSD', '{"capacity":"4TB","interface":"SATA III","read_mbps":560,"write_mbps":530,"form_factor":"2.5 inch"}', 299, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Samsung+870+EVO+4TB","condition":"new"},{"store":"Allegro","url":"https://allegro.pl/listing?string=Samsung+870+EVO+4TB","condition":"new"}]', true),
('storage', 'Seagate', 'IronWolf 8TB NAS HDD', '{"capacity":"8TB","interface":"SATA III","rpm":7200,"cache_mb":256,"form_factor":"3.5 inch","nas_optimized":true}', 199, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Seagate+IronWolf+8TB","condition":"new"}]', true),
('storage', 'WD', 'Red Plus 6TB NAS HDD', '{"capacity":"6TB","interface":"SATA III","rpm":5400,"cache_mb":128,"form_factor":"3.5 inch","nas_optimized":true}', 149, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=WD+Red+Plus+6TB","condition":"new"}]', true),
('storage', 'Samsung', '990 Pro 2TB NVMe', '{"capacity":"2TB","interface":"PCIe 4.0 NVMe","read_mbps":7450,"write_mbps":6900,"form_factor":"M.2 2280"}', 149, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Samsung+990+Pro+2TB","condition":"new"},{"store":"Allegro","url":"https://allegro.pl/listing?string=Samsung+990+Pro+2TB","condition":"new"}]', true),
('storage', 'WD', 'Black SN850X 2TB NVMe', '{"capacity":"2TB","interface":"PCIe 4.0 NVMe","read_mbps":7300,"write_mbps":6600,"form_factor":"M.2 2280"}', 139, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=WD+Black+SN850X+2TB","condition":"new"}]', true),
('storage', 'Crucial', 'P3 Plus 2TB NVMe', '{"capacity":"2TB","interface":"PCIe 4.0 NVMe","read_mbps":5000,"write_mbps":4200,"form_factor":"M.2 2280"}', 89, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Crucial+P3+Plus+2TB","condition":"new"}]', true),
('storage', 'Kingston', 'KC3000 2TB NVMe', '{"capacity":"2TB","interface":"PCIe 4.0 NVMe","read_mbps":7000,"write_mbps":7000,"form_factor":"M.2 2280"}', 129, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Kingston+KC3000+2TB","condition":"new"}]', true),
('storage', 'Seagate', 'Exos X18 18TB Enterprise HDD', '{"capacity":"18TB","interface":"SATA III","rpm":7200,"cache_mb":256,"form_factor":"3.5 inch","enterprise":true}', 349, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Seagate+Exos+X18+18TB","condition":"new"}]', true),

-- RAM
('ram', 'Crucial', '32GB DDR4-3200 SODIMM Kit (2x16GB)', '{"capacity":"32GB","type":"DDR4","speed":"3200MHz","form_factor":"SODIMM","ecc":false}', 59, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Crucial+32GB+DDR4+SODIMM","condition":"new"}]', true),
('ram', 'Kingston', '64GB DDR4-3200 ECC UDIMM Kit (2x32GB)', '{"capacity":"64GB","type":"DDR4 ECC","speed":"3200MHz","form_factor":"UDIMM","ecc":true}', 149, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Kingston+64GB+DDR4+ECC","condition":"new"}]', true),
('ram', 'Corsair', '32GB DDR5-5600 SODIMM Kit (2x16GB)', '{"capacity":"32GB","type":"DDR5","speed":"5600MHz","form_factor":"SODIMM","ecc":false}', 79, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Corsair+32GB+DDR5+SODIMM","condition":"new"}]', true),
('ram', 'Samsung', '16GB DDR4-3200 SODIMM', '{"capacity":"16GB","type":"DDR4","speed":"3200MHz","form_factor":"SODIMM","ecc":false}', 29, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Samsung+16GB+DDR4+SODIMM","condition":"new"},{"store":"Allegro","url":"https://allegro.pl/listing?string=Samsung+16GB+DDR4+SODIMM","condition":"new"}]', true),

-- GPUs (for AI/ML homelabs)
('gpu', 'NVIDIA', 'RTX 3060 12GB', '{"vram":"12GB GDDR6","cuda_cores":3584,"tdp_w":170,"pcie":"PCIe 4.0 x16","form_factor":"dual-slot"}', 299, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=RTX+3060+12GB","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=RTX+3060+12GB","condition":"used"}]', true),
('gpu', 'NVIDIA', 'RTX 4060 8GB', '{"vram":"8GB GDDR6","cuda_cores":3072,"tdp_w":115,"pcie":"PCIe 4.0 x16","form_factor":"dual-slot"}', 299, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=RTX+4060+8GB","condition":"new"}]', true),
('gpu', 'NVIDIA', 'Tesla P40 24GB (used)', '{"vram":"24GB GDDR5","cuda_cores":3840,"tdp_w":250,"pcie":"PCIe 3.0 x16","form_factor":"dual-slot","note":"Data center card, no display output"}', 199, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=NVIDIA+Tesla+P40","condition":"used"}]', true),
('gpu', 'AMD', 'RX 6600 8GB', '{"vram":"8GB GDDR6","stream_processors":1792,"tdp_w":132,"pcie":"PCIe 4.0 x8","form_factor":"dual-slot"}', 199, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=AMD+RX+6600+8GB","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=AMD+RX+6600","condition":"used"}]', true),

-- HBA / NIC Cards
('hba', 'LSI', '9300-8i HBA (IT mode)', '{"ports":"8x SAS/SATA","pcie":"PCIe 3.0 x8","max_drives":256,"note":"Flashed to IT mode for ZFS/TrueNAS"}', 79, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=LSI+9300-8i+IT+mode","condition":"used"}]', true),
('hba', 'LSI', '9207-8i HBA (IT mode)', '{"ports":"8x SAS/SATA","pcie":"PCIe 3.0 x8","max_drives":256,"note":"Flashed to IT mode"}', 49, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=LSI+9207-8i+IT+mode","condition":"used"}]', true),
('nic', 'Intel', 'X550-T2 10GbE NIC', '{"ports":"2x 10GbE RJ45","pcie":"PCIe 3.0 x4","form_factor":"low-profile"}', 149, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Intel+X550-T2","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Intel+X550-T2","condition":"used"}]', true),
('nic', 'Mellanox', 'ConnectX-3 10GbE SFP+', '{"ports":"2x 10GbE SFP+","pcie":"PCIe 3.0 x8","form_factor":"low-profile"}', 29, 'EUR', '[{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Mellanox+ConnectX-3+10GbE","condition":"used"}]', true),
('nic', 'Intel', 'I350-T4 Quad GbE NIC', '{"ports":"4x GbE RJ45","pcie":"PCIe 2.1 x4","form_factor":"low-profile"}', 49, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Intel+I350-T4","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=Intel+I350-T4","condition":"used"}]', true),

-- Networking Accessories
('accessory', 'Various', 'DAC SFP+ 10G Cable 1m', '{"type":"DAC","speed":"10GbE","length":"1m","compatibility":"Ubiquiti/MikroTik/Cisco"}', 15, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=DAC+SFP%2B+10G+1m","condition":"new"}]', true),
('accessory', 'Various', 'SFP+ Fiber Transceiver 10G SR', '{"type":"SFP+ transceiver","speed":"10GbE","wavelength":"850nm","distance":"300m OM3"}', 12, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=SFP%2B+10G+SR+transceiver","condition":"new"}]', true),
('accessory', 'Panduit', '24-Port Cat6 Patch Panel', '{"ports":24,"type":"patch panel","standard":"Cat6","form_factor":"1U rack"}', 49, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=24+port+cat6+patch+panel","condition":"new"}]', true),

-- Rack & Enclosures
('rack', 'Startech', '12U Open Frame Server Rack', '{"units":12,"depth_mm":610,"form_factor":"open frame","load_kg":136}', 199, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Startech+12U+open+frame+rack","condition":"new"}]', true),
('rack', 'Navepoint', '9U Wall Mount Network Cabinet', '{"units":9,"depth_mm":450,"form_factor":"wall mount","load_kg":60}', 149, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=9U+wall+mount+network+cabinet","condition":"new"}]', true),
('rack', 'Tripp Lite', '42U Standard Server Rack', '{"units":42,"depth_mm":1070,"form_factor":"floor standing","load_kg":1360}', 799, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Tripp+Lite+42U+server+rack","condition":"new"}]', true),

-- PDU
('pdu', 'APC', 'AP7920B Rack PDU 1U 8-outlet', '{"outlets":8,"amps":20,"form_factor":"1U rack","metered":true}', 199, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=APC+AP7920B+PDU","condition":"new"},{"store":"eBay","url":"https://www.ebay.com/sch/i.html?_nkw=APC+AP7920B","condition":"used"}]', true),
('pdu', 'Tripp Lite', 'PDUMH20 Metered PDU 1U 16-outlet', '{"outlets":16,"amps":20,"form_factor":"1U rack","metered":true}', 149, 'EUR', '[{"store":"Amazon DE","url":"https://www.amazon.de/s?k=Tripp+Lite+PDUMH20","condition":"new"}]', true);
